# Generated by Django 4.0.6 on 2022-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='New Question', max_length=255, verbose_name='Question Title'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Quiasdz', max_length=255, verbose_name='Quiz Title'),
        ),
    ]
