# Generated by Django 4.0.6 on 2022-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_options_alter_question_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, verbose_name='Quiz Title'),
        ),
    ]
